# ML Zoomcamp 2025
## Module 1 - Introduction Homework

## Q1. Pandas version

What version of Pandas did I install?

In [138]:
import pandas as pd
import numpy as np

pd.__version__

'3.0.5'

## Loading the dataset

In [139]:
df = pd.read_csv('car_fuel_efficiency.csv')
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

## Q2. Records count

How many records are in the dataset?

In [140]:
df.shape

(9704, 11)

## Q3. Fuel types

In [141]:
df['fuel_type'].nunique()

2

## Q4. Missing values

In [142]:
df.isnull().sum()
#4

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

## Q5. Max fuel efficiency

In [143]:
df[df['origin']=='Asia']['fuel_efficiency_mpg'].max()
#23.75

np.float64(23.759122836520497)

## Q6. Median value of horsepower

## 6-1. the median value of the horsepower

In [144]:
df['horsepower'].mean()  #149.65

np.float64(149.65729212983547)

## 6.2-the most frequent value of the horsepower

In [145]:
df['horsepower'].value_counts()    #152

horsepower
152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
        ...
40.0       1
57.0       1
245.0      1
252.0      1
61.0       1
Name: count, Length: 192, dtype: int64

## 6.3-fill the missing values with the most frequent value.

In [146]:
df['horsepower'].fillna(152)

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

## 6.4-the median value of horsepower once again.

In [147]:
df.horsepower.mean()
# it hasn't changed because we didn't assign the filled values back to the dataframe. We need to do df['horsepower'] = df['horsepower'].fillna(152) to update the dataframe.

np.float64(149.65729212983547)

## Q7. Sum of weights

## 7.1

In [148]:
asia_cars = df[df['origin']=='Asia']
asia_cars

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
8,250,1.0,174.0,2714.219310,10.3,2016,Asia,Diesel,Front-wheel drive,-1.0,16.823554
12,320,5.0,145.0,2783.868974,15.1,2010,Asia,Diesel,All-wheel drive,1.0,16.175820
14,200,6.0,160.0,3582.687368,14.9,2007,Asia,Diesel,All-wheel drive,0.0,11.871091
20,150,3.0,197.0,2231.808142,18.7,2011,Asia,Gasoline,Front-wheel drive,1.0,18.889083
21,160,4.0,133.0,2659.431451,NaN,2016,Asia,Gasoline,Front-wheel drive,-1.0,16.077730
...,...,...,...,...,...,...,...,...,...,...,...
9688,260,4.0,NaN,3948.404625,15.5,2018,Asia,Diesel,All-wheel drive,-1.0,11.054830
9692,180,3.0,188.0,3680.341381,18.0,2016,Asia,Gasoline,Front-wheel drive,1.0,11.711653
9693,280,2.0,148.0,2545.070139,15.6,2012,Asia,Diesel,All-wheel drive,0.0,17.202782
9698,180,1.0,131.0,3107.427820,13.2,2005,Asia,Gasoline,Front-wheel drive,-2.0,13.933716
9703,270,3.0,140.0,2908.043477,14.7,2005,Asia,Diesel,All-wheel drive,-1.0,14.884467

## 7.2

In [149]:
asia_cars = asia_cars.loc[:,['vehicle_weight' , 'model_year']]
asia_cars

      vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

## 7.3

In [150]:
asia_cars=asia_cars.head(7)
asia_cars

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

## 7.4

In [151]:
X = asia_cars.to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

## 7.5

In [152]:
XTX= X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

## 7.6

In [153]:
XTX.shape  # it should be symmetric and square, so it should be (2,2) because we have 2 features in the dataset.

(2, 2)

In [154]:
inv = np.linalg.inv(XTX)
inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

## 7.7

In [155]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

## 7.8

In [156]:
w=inv.dot(X.T).dot(y)
w

array([0.01386421, 0.5049067 ])

## 7.9

In [157]:
np.sum(w)  #0.51

np.float64(0.5187709081074016)